[package]
name = "bdk-wasm"
version = "0.1.0"
authors = ["Dario Anongba Varela <dario.anongba@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["bdk_esplora"]
debug = ["console_error_panic_hook"]
metamask = []
bitcoind_rpc = ["bdk_bitcoind_rpc"]

[dependencies]
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"
anyhow = "1.0.93"
console_error_panic_hook = { version = "0.1.7", optional = true }
thiserror = "2.0.3"
serde_json = "1.0.133"
serde = { version = "1.0.215", default-features = false, features = ["derive"] }
js-sys = "0.3.72"
serde-wasm-bindgen = "0.6.5"
wee_alloc = "0.4.5"

# Compatibility to compile to WASM
getrandom = { version = "0.2.15", features = ["js"] }
ring = { version = "0.17.8", features = ["wasm32_unknown_unknown_js"] }

# Bitcoin dependencies
bdk_wallet = { git = "https://github.com/bitcoindevkit/bdk", branch = "master", features = [
    "keys-bip39",
] }
bdk_esplora = { git = "https://github.com/bitcoindevkit/bdk", branch = "master", default-features = false, features = [
    "async-https",
], optional = true }
bitcoin = { version = "0.32.4", default-features = false }
miniscript = "12.2.0"
bdk_bitcoind_rpc = { version = "0.16.0", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.45"
web-sys = { version = "0.3.72", features = ["console"] }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
