name: Check if Release

on:
  workflow_call:
    outputs:
      IS_RELEASE:
        description: "True if Cargo.toml version has been updated"
        value: ${{ jobs.check-is-release.outputs.is_release }}

jobs:
  check-is-release:
    name: Check Cargo.toml for Version Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          # we need this commit + the last so we can compare below
          fetch-depth: 2

      - name: Compare Cargo.toml versions
        id: check-release
        run: |
          prev_commit="${{ github.event.before }}"
          echo "Previous commit: $prev_commit"

          # Extract versions
          get_version() { grep -E '^version\s*=' | sed -E 's/version\s*=\s*"([^"]+)"/\1/'; }
          current_version=$(get_version < Cargo.toml)
          previous_version=$(git show "$prev_commit:Cargo.toml" | get_version)
          echo "Current version: $current_version"
          echo "Previous version: $previous_version"

          if [ "$current_version" != "$previous_version" ]; then
            echo "Version bump detected."
            echo "is_release=true" >> "$GITHUB_OUTPUT"
          else
            echo "No version bump detected."
            echo "is_release=false" >> "$GITHUB_OUTPUT"
          fi
    outputs:
      is_release: ${{ steps.check-release.outputs.is_release }}
