name: Publish Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@4f647fc679bcd3b11499ccb42104547c83dabe96
        with:
          toolchain: stable
      - name: Install wasm-pack
        run: curl https://raw.githubusercontent.com/rustwasm/wasm-pack/a3a48401795cd4b3afe1d74568c93675a04f3970/installer/init.sh -sSf | sh -s -- -f
      - name: Rust Cache
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab
      - name: Build
        run: wasm-pack build --scope metamask --features "esplora"
      - name: Dry Run Publish
        run: wasm-pack publish --access=public -- --dry-run
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          wasm-pack publish --access=public
