name: Publish Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  build-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@4f647fc679bcd3b11499ccb42104547c83dabe96
        with:
          toolchain: stable
      - name: Install wasm-pack
        run: curl https://raw.githubusercontent.com/rustwasm/wasm-pack/a3a48401795cd4b3afe1d74568c93675a04f3970/installer/init.sh -sSf | sh -s -- -f
      - name: Rust Cache
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab
      - name: Build
        run: wasm-pack build --scope metamask --features "esplora"
      - name: Upload WASM build
        uses: actions/upload-artifact@v4
        with:
          name: wasm-pkg
          path: pkg
          retention-days: 1

  publish-npm-dry-run:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Download WASM build
        uses: actions/download-artifact@v4
        with:
          name: wasm-pkg
          path: pkg
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Dry Run Publish
        working-directory: pkg
        run: npm publish --access=public --dry-run
      - name: Publish
        working-directory: pkg
        run: npm publish --access=public
